remote_theme: allejo/jekyll-docs-theme
project:
  version: 4.0.0
  download_url: https://github.com/lildude/phpsmug/releases
license:
  software: MIT License
  software_url: http://opensource.org/licenses/MIT
  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/
ui:
  header:
    color1: "#669900"
    color2: "#365100"
    trianglify: true
links:
  header:
    - title: GitHub
      url: https://github.com/allejo/jekyll-docs-theme
  footer:
    - title: GitHub
      url: https://github.com/allejo/jekyll-docs-theme
    - title: Issues
      url: https://github.com/allejo/jekyll-docs-theme/issues?state=open
