remote_theme: allejo/jekyll-docs-theme
project:
  version: 4.0.0
  download_url: https://github.com/lildude/phpsmug/releases
license:
  software: MIT License
  software_url: http://opensource.org/licenses/MIT
  docs: CC BY 3.0
  docs_url: http://creativecommons.org/licenses/by/3.0/
ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true
